### ISSUE TITLE
Request for pytorch NER tagging

### ISSUE THREAD

**Issue by sathish331977** [bentrevett/pytorch-pos-tagging#1]
Can you please write a tutorial on NER tagging using pytorch.

**Comment by bentrevett** [comment]
NER tagging should work the same way as POS tagging. You have a model that gives a prediction for each element in the input sequence. With POS tagging the prediction is the tag given to that token and with NER the prediction is if that token is a named element. 

If you know of any suitable NER datasets I can add them to the tutorials.

**Comment by sathish331977** [comment]
Thank you, i will refer to POS tagging.

**Comment by antgr** [comment]
Here is a dataset for NER:
https://raw.githubusercontent.com/Franck-Dernoncourt/NeuroNER/master/neuroner/data/conll2003/en/valid.txt 
https://raw.githubusercontent.com/Franck-Dernoncourt/NeuroNER/master/neuroner/data/conll2003/en/train.txt
https://raw.githubusercontent.com/Franck-Dernoncourt/NeuroNER/master/neuroner/data/conll2003/en/test.txt
Is it really pos and ner the same? Maybe it is. But I ask this because for NER is used the iob tagging
https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging)
which means that after a b you have one or more i and then o, and you cannot for example have i-b-o etc

**Comment by bentrevett** [comment]
I believe so - the task in each of them is to produce an output for each item in the sequence. 

In POS tagging you are outputting the POS tag for each item in the sequence, for NER you are outputting a tag for each item in the sequence.

Yes, your model should not output an I-tag if it's not between a B-tag and an O-tag - but that is something the model should learn itself, correct?

**Comment by antgr** [comment]
Yes, you are correct. Thanks
